workflows:
  ios-unsigned-app:
    name: iOS Unsigned .app Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Clean project
        script: flutter clean

      - name: Build iOS unsigned app
        script: flutter build ios --release --no-codesign

      - name: Collect .app
        script: |
          mkdir -p build/output
          cp -R build/ios/iphoneos/Runner.app build/output/

    artifacts:
      - build/output/Runner.app
